BOTTLE_CONTENT_MANAGER_API_PORT = 8081
BOTTLE_DEORATOR_PORTFOLIOS_API_PORT = 8082
BOTTLE_DEORATOR_TAGS_API_PORT = 8083
BOTTLE_DEORATOR_VOTES_API_PORT = 8084

USE_SOLR_AS_PERSISTENCE = True
SOLR_URL = 'http://localhost:8983/solr'
DECORATION_SOLR_FIELD_0 = 'portfolios'
DECORATION_SOLR_FIELD_1 = 'tags'
